name: Backend Continuous Integration

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run linter
        run: pipenv run lint

      - name: Run tests
        run: pipenv run test

  build:
    needs: lint-and-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build --tag mp-backend:latest .